const contractAddress = "0x3f8129C53e97755408Da4014983a4054E465E9Aa"; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "Salve! Bem-vindo ao projeto de NFT dos Crias";
const welcome_h2 = "Conecte na Metamask para continuar";
const welcome_p = 'O CRIAS é um projeto de arte NFT que homenageia a cultura do Funk e das Favelas Brasileiras, expondo o estilo inigualável dos Chavosos. Todo o projeto foi desenvolvido por @naosoutaoruim, morador de favela e mais um na batalha contra o sistema.';
const h1_presale_coming_soon = "Em breve";
const h1_presale_mint = "Pre-venda Aberta!";
const h1_public_mint = "Venda Aberta!";
const h2_presale_coming_soon = "Fim da pre-venda!";
const h2_presale_mint = "Fim das vendas";
const p_presale_coming_soon = "Estamos trabalhando pesado aqui. Fica ligado!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "Venda publica aberta!";
const button_presale_coming_soon = "Entre na lista";
const button_presale_mint_whitelisted = "Garanta seu NFT dos CRIAS";
const button_presale_mint_not_whitelisted = "Entre na lista";
const button_presale_already_minted = "Faça parte da comunidade";
const button_public_mint = "Garanta seu NFT dos CRIAS";
const mint_failed = "Algo deu errado. Tente Novamente";
